config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'dashboards#index'
  get '/simulate', to: 'dashboards#simulate'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


end

app/controllers/dashboards_controller.rb
require 'rest-client'

class DashboardsController < ApplicationController

  def index

  end

  def simulate
    data =
        {
            'to' => '/topics/all',
            'data' => {
              'gate' => '1F',
              'locationIds' => ['37.621414:-122.381134', '37.78629:-122.401375', '37.775585:-122.3901']
            }
        }.to_json

    headers = {
        'Authorization': 'key=AIzaSyAgcSS0Nk6crjjwYMJwmhnhvH3Yq7pBClQ',
        content_type: :json,
        accept: :json}

    RestClient.post "https://fcm.googleapis.com/fcm/send", data, headers

    render :nothing => true
  end

  def webhook_listen
    'AIzaSyBBP9hIRe8Re6oHqD_-QBXVK2wyi-Bq9z4'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_form.html.erb
<%= form_for(dashboard) do |f| %>
  <% if dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

      <ul>
      <% dashboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboards/edit.html.erb
<h1>Editing Dashboard</h1>

<%= render 'form', dashboard: @dashboard %>

<%= link_to 'Show', @dashboard %> |
<%= link_to 'Back', dashboards_path %>

app/views/dashboards/index.html.erb
Hit this button to mimick the plane has landed.
<button id="simulate" onclick="simulate()">Simulate Flight Landed</button>
<div class="result"></div>

app/views/dashboards/new.html.erb
<h1>New Dashboard</h1>

<%= render 'form', dashboard: @dashboard %>

<%= link_to 'Back', dashboards_path %>

app/views/dashboards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_dashboard_path(@dashboard) %> |
<%= link_to 'Back', dashboards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LastmileclubWeb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>